#!/usr/bin/env python

import argparse

from xsql import run


parser = argparse.ArgumentParser()
parser.add_argument("url", help="the url connection string")
parser.add_argument("--command", "-c", help="a raw sql command to run")
parser.add_argument("--file", "-f", help="a file to run")
parser.add_argument("--output", "-o", help="where to write output to")

args = parser.parse_args()

run(args)
